apiVersion: v1
kind: ReplicationController
metadata:
  name: custom-server
  namespace: custom-apiserver
  labels:
    apiserver: "true"
spec:
  replicas: 1
  selector:
    apiserver: "true"
  template:
    metadata:
      labels:
        apiserver: "true"
    spec:
      serviceAccountName: apiserver
      containers:
      - name: apiserver
        image: quay.io/programming-kubernetes/custom-apiserver:latest
        imagePullPolicy: Always
        command: [ "/custom-apiserver", "--etcd-servers=http://localhost:2379" ]
      - name: etcd
        image: quay.io/coreos/etcd:v3.2.24
